name: Flakiness Check

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  repeat-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run tests 5 times each
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
        run: npx playwright test --repeat-each=5
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: flakiness-report
          path: playwright-report/
          retention-days: 14
